import exception
import fib
print(exception.greet('Student'))
print(fib.fib(20))